### ISSUE TITLE
Any plans for implementing oAuth 2.0?

### ISSUE THREAD

**Issue by jusfreeman** [eileenmcnaughton/nz.co.fuzion.civixero#62] opened 2019-10-30 23:04 UTC
Any plans for implementing oAuth 2.0 as Xero is pushing developers to implement this for Xero integration.

https://devblog.xero.com/tagged/oauth2

Agileware Ref: CIVIXERO-36

**Comment by eileenmcnaughton** [comment] 2019-10-31 01:50
I thought we had?

**Comment by kenwest** [comment] 2019-12-24 03:09
I can't see that it has been implemented, @eileenmcnaughton - the packages/Xero/Xero.php looks like the old API and it's 3 years old.

**Comment by dcapslock** [comment] 2019-12-29 03:59
The instructions for setting up civixero mention a private app. As per https://developer.xero.com/documentation/auth-and-limits/private-applications

> OAuth1.0a is in the process of being deprecated and new private apps can no longer be created.

and per https://developer.xero.com/documentation/oauth2/overview

> Early December 2019 - No new OAuth 1.0a apps created.

So looks like no new instances of CiviXero can be setup until it supports OAuth2.0

**Comment by Upperholme** [comment] 2020-01-09 11:50
I'm just trying to set up an integration now. https://developer.xero.com/myapps/ is demanding an OAuth 2.0 redirect URI ?

**Comment by Upperholme** [comment] 2020-01-09 12:04
https://developer.xero.com/documentation/libraries/php

**Comment by Upperholme** [comment] 2020-01-09 12:43
This looks like a showstopper for the time being. Which is frustrating. Any insight into whether/when this might be addressed would be most helpful. Not sure I can offer any more practical help, other than as a willing tester.

**Comment by agileware-justin** [comment] 2020-01-09 22:57
Agileware can do this development work, seeing as it's a blocker to new Xero accounts this would stop on-boarding of new CiviCRM sites utilising Xero.

ETA would be in the next 1 to 2 months.

If any of you want to help fund development just let me know via email sales@agileware.com.au

Ping @Upperholme @dcapslock @kenwest

**Comment by eileenmcnaughton** [comment] 2020-01-09 22:58
Thanks @agileware-justin

**Comment by Upperholme** [comment] 2020-01-10 09:32
This is welcome news, thanks @agileware-justin. In term of funding I'll certainly take that up with my client, although as we aren't yet clear on whether the Xero integration will actually deliver the results that we need - we were setting up the integration to test and gain a deeper understanding of capabilities and limitations before implementing into production - I'm not confident that they'll be willing at this stage.

**Comment by dcapslock** [comment] 2020-01-10 09:49
I am implementing for a NFP Radio Station with limited budget. I am happy to contribute in any way, probably testing etc. However the only resource I have to give is my own time.

**Comment by Upperholme** [comment] 2020-02-10 09:34
Just wondering if there's been any update on this, one month on? Not wishing to nag in any way, but simply so that I can feed back.

**Comment by agileware-justin** [comment] 2020-02-10 22:22
@Upperholme probably next month, we're been flat out on other projects.

**Comment by eileenmcnaughton** [comment] 2020-02-10 22:27
Parvez (Veda) had some money maybe on this - one of his staff  contacted me & I was trying to figure out if I had capacity before losing track of where the message came from...

**Comment by agileware-justin** [comment] 2020-02-10 22:40
@eileenmcnaughton got for it if you have time

Otherwise anyone can submit funding as per my previous invitation https://github.com/eileenmcnaughton/nz.co.fuzion.civixero/issues/62#issuecomment-572795376

**Comment by eileenmcnaughton** [comment] 2020-02-10 22:41
@agileware-justin Well - the capacity hasn't emerged - if it does I'll let you know & work on it - but don't let that possibility stop you!

**Comment by agileware-justin** [comment] 2020-02-10 22:42
I won't!!

**Comment by veda-consulting** [comment] 2020-03-02 13:37
@eileenmcnaughton @agileware-justin @Upperholme we have started working on OAuth 2.0. Should be done in a couple of weeks. Shout if anyone else is on it (I've reached out to @petednz as I saw a stackexchange question from him).

**Comment by Upperholme** [comment] 2020-03-02 14:01
Excellent news. Happy assist with testing.

**Comment by petednz** [comment] 2020-03-02 18:46
Thanks for bringing me on this thread. hadn't spotted it last night.

**Comment by agileware-justin** [comment] 2020-03-02 20:02
@veda-consulting cool, best of luck and thanks for letting everyone know.

**Comment by dcapslock** [comment] 2020-03-02 20:07
Great news. Will happily test.

________________________________

**Comment by eileenmcnaughton** [comment] 2020-03-02 20:08
Thanks  @veda-consulting  - I'm conscious I didn't reply when you pinged me so apologies for that!

**Comment by veda-consulting** [comment] 2020-03-04 12:51
@eileenmcnaughton no probs, we assumed your super busy. This is Parvez by the way! We're hoping to have a fork of the repo early next week for testing, if all is good we'll PR back.

**Comment by veda-consulting** [comment] 2020-03-17 16:39
@jusfreeman @eileenmcnaughton @kenwest @dcapslock @Upperholme @petednz first alpha versions ready to test on our repo (we'll PR back to this repo once its been through to Beta)

To download the branch, navigate to https://github.com/veda-consulting/nz.co.fuzion.civixero/tree/OAuth2 and click ‘Clone or download’ and click ‘Download Zip’ which will download ‘OAuth2’ branch

**Comment by agileware-justin** [comment] 2020-03-17 22:10
@veda-consulting good work and thank you very much for this contribution.

Where did you want feedback on this? When you submit a PR or elsewhere?

A quick review and my initial thought was: why is Guzzle being bundled with the extension when it's already bundled with CiviCRM?

**Comment by veda-consulting** [comment] 2020-03-18 12:26
@agileware-justin thanks for the feedback - for the sake of ease lets keep the feedback on this thread. I'll get the guys to check.

**Comment by petednz** [comment] 2020-03-27 21:22
@veda-consulting we set up two sites using this new OAuth and both authorised as intended and synching etc was as expected. Thank you, thank you, thank you.

**Comment by dcapslock** [comment] 2020-04-18 11:29
@eileenmcnaughton, I have tested now and all seems good. I just went through and did the contact sync and did the matching and exclusions. Only one 'error' and that was after authorise it took me to a URL not correct for wordpress. The error URL was https://www.alive905.com.au/civicrm/xero/authorize, even though I did use the correct Authorise URL in the app. Thanks very much for this! I have good news to report the the Alive 90.5 FM Board on Tuesday night. Our Treasurer is going to be very happy as we have about 120 renewals due in June (annual renewal date for all members).

**Comment by petednz** [comment] 2020-04-19 03:08
Thanks for the feedback @dcapslock but to be clear, this improvement was by Parvez' crew at Veda Consulting. @veda-consulting @eileenmcnaughton anything else you think is required before a new version gets released? @agileware-justin 's comment re Guzzle perhaps?

**Comment by eileenmcnaughton** [comment] 2020-04-19 03:10
@petednz I'm just not sure how best to manage the transition for existing sites - I haven't tested it but I think I at least need some instructions / an announcement?

**Comment by petednz** [comment] 2020-04-19 03:31
I don't think there is any change for existing sites - it is only a change if/when their existing authorisation runs out

**Comment by petednz** [comment] 2020-04-19 03:32
if/when we do our next one i will make sure that documentation is thorough but from memory what Veda provided was all that was necessary. Simpler than before by a long shot.

**Comment by eileenmcnaughton** [comment] 2020-04-25 03:38
I have merged the PR - I still haven't gotten my head around what needs to be communicated / a release strategy but I figured it pretty much had to be merged & the rest can be resolved post-merge

**Comment by petednz** [comment] 2020-04-25 06:33
This needs to be released. Anyone downloading this extension without Veda new goodies will be sad and frustrated. The new documentation by Veda in the readme is good enough imo

**Comment by eileenmcnaughton** [comment] 2020-04-26 02:49
OK - I'll go with your recommendation

**Comment by eileenmcnaughton** [comment] 2020-04-26 02:52
2.0 released

**Closed by eileenmcnaughton** 2020-04-26 02:52 UTC
